name: acuant_flutter_plugin_example
description: Demonstrates how to use the acuant_flutter_plugin plugin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  acuant_flutter_plugin:
    # When depending on this package from a real application you should use:
    #   acuant_flutter_plugin: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  
  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true 